workspace(name = "example_001")

local_repository(
    name = "salesforce_rules_mybuilder",
    path = "../..",
)

load("@salesforce_rules_mybuilder//mybuilder:repositories.bzl", "rules_mybuilder_dependencies")
rules_mybuilder_dependencies()

