workspace(name = "example_002")


local_repository(
    name = "salesforce_rules_mybuilder",
    path = "../..",
)

load("@salesforce_rules_mybuilder//mybuilder:repositories.bzl", "rules_mybuilder_dependencies")
rules_mybuilder_dependencies()

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
