workspace(name = "example_002")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

local_repository(
    name = "rules_mybuilder",
    path = "../..",
)

load("@rules_mybuilder//mybuilder:repositories.bzl", "rules_mybuilder_dependencies")
rules_mybuilder_dependencies()

