java_library(
    name = "worker",
    srcs = [
        "GenericWorker.java",
        "Processor.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/google/devtools/build/lib/worker",
    ],
)
