java_library(
    name = "worker",
    srcs = [
        "GenericWorker.java",
        "Processor.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/google/devtools/build/lib/worker",
        "@mybuilder_rules_org_slf4j_api",
        "@mybuilder_rules_org_slf4j_jul_to_slf4j",
        "@mybuilder_rules_org_slf4j_jcl_over_slf4j",
    ],
)
