package(default_visibility = ["//visibility:private"])

filegroup(
    name = "slf4j_simple_properties",
    srcs = [
        "simplelogger.properties",
    ],
    visibility = ["//visibility:public"],
)
